In [3]:
import pandas as pd
import numpy as np
import neattext as nt
import neattext.functions as nfx
import string
import text2emotion as te
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.io as sio
import math
from scipy.stats import multivariate_normal

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [2]:
df = pd.read_csv("Secret Recipe(NoDup).csv")

In [4]:
#Noise Scan
df['Text'].apply(lambda x : nt.TextFrame(x).noise_scan()['text_noise'])

0       14.935065
1       14.743590
2       11.038961
3       14.743590
4       11.235955
          ...
4584    15.172414
4585    16.666667
4586    16.176471
4587    14.705882
4588    18.518519
Name: Text, Length: 4589, dtype: float64

In [5]:
df['Text']

0       b'RT @mhazimhamdan: Ni air starbuck rahsia dar...
1       b'RT @peteprodge: Brewdog is trending because ...
2       b'The secret recipe to progress - The Up Devot...
3       b'RT @peteprodge: Brewdog is trending because ...
4       b'RT @Davidoooey: New Secret 1.6 Food Recipes\...
                              ...
4584    b"RT @Gatonetillo: @kfc Is animal cruelty part...
4585    b"@kfc Is animal cruelty part of @KFC's secret...
4586    b'RT @princess_antifa: i released my secret re...
4587    b'Another Great #RECIPE Post from #FTHM\n\nPle...
4588    b"Me: when I discovered the 'secret recipe' of...
Name: Text, Length: 4589, dtype: object

In [7]:
df.head()

,Unnamed: 0,Time,Id,Username,Text,userhandles
0,NaN,6/10/2021 9:07,1.402920e+18,�??�?��?��???�??��??�,b'RT @mhazimhamdan: Ni air starbuck rahsia dar...,[@mhazimhamdan:]
1,0.0,6/10/2021 9:04,1.402910e+18,Richard Gale,b'RT @peteprodge: Brewdog is trending because ...,[@peteprodge:]
2,1.0,6/10/2021 9:04,1.402910e+18,The Up! Devo,b'The secret recipe to progress - The Up Devot...,[]
3,2.0,6/10/2021 9:04,1.402910e+18,Ben Marlow,b'RT @peteprodge: Brewdog is trending because ...,[@peteprodge:]
4,3.0,6/10/2021 9:01,1.402910e+18,UnLe,b'RT @Davidoooey: New Secret 1.6 Food Recipes\...,[@Davidoooey:]

In [8]:
df['clean_text'] = df['Text'].apply(nfx.remove_userhandles)

In [9]:
df.head()

,Unnamed: 0,Time,Id,Username,Text,userhandles,clean_text
0,NaN,6/10/2021 9:07,1.402920e+18,�??�?��?��???�??��??�,b'RT @mhazimhamdan: Ni air starbuck rahsia dar...,[@mhazimhamdan:],b'RT Ni air starbuck rahsia dari barista. Dr...
1,0.0,6/10/2021 9:04,1.402910e+18,Richard Gale,b'RT @peteprodge: Brewdog is trending because ...,[@peteprodge:],b'RT Brewdog is trending because of its awfu...
2,1.0,6/10/2021 9:04,1.402910e+18,The Up! Devo,b'The secret recipe to progress - The Up Devot...,[],b'The secret recipe to progress - The Up Devot...
3,2.0,6/10/2021 9:04,1.402910e+18,Ben Marlow,b'RT @peteprodge: Brewdog is trending because ...,[@peteprodge:],b'RT Brewdog is trending because of its awfu...
4,3.0,6/10/2021 9:01,1.402910e+18,UnLe,b'RT @Davidoooey: New Secret 1.6 Food Recipes\...,[@Davidoooey:],b'RT New Secret 1.6 Food Recipes\n\xe2\x80\x...

In [11]:
# Remove Hashtags
df['clean_text'].apply(nfx.remove_hashtags)

0       b'RT   Ni air starbuck rahsia dari barista. Dr...
1       b'RT   Brewdog is trending because of its awfu...
2       b'The secret recipe to progress - The Up Devot...
3       b'RT   Brewdog is trending because of its awfu...
4       b'RT   New Secret 1.6 Food Recipes\n\xe2\x80\x...
                              ...
4584    b"RT     Is animal cruelty part of   secret re...
4585    b"  Is animal cruelty part of   secret recipe?...
4586    b'RT   i released my secret recipe in the flee...
4587    b'Another Great   Post from   Consider Sponsor...
4588    b"Me: when I discovered the 'secret recipe' of...
Name: clean_text, Length: 4589, dtype: object

In [12]:
# Remove Custom Pattern
df['clean_text'].apply(lambda x: nfx.remove_custom_pattern(x, term_pattern=r'&#\S+'))

0       b'RT   Ni air starbuck rahsia dari barista. Dr...
1       b'RT   Brewdog is trending because of its awfu...
2       b'The secret recipe to progress - The Up Devot...
3       b'RT   Brewdog is trending because of its awfu...
4       b'RT   New Secret 1.6 Food Recipes\n\xe2\x80\x...
                              ...
4584    b"RT     Is animal cruelty part of   secret re...
4585    b"  Is animal cruelty part of   secret recipe?...
4586    b'RT   i released my secret recipe in the flee...
4587    b'Another Great #RECIPE Post from #FTHM\n\nPle...
4588    b"Me: when I discovered the 'secret recipe' of...
Name: clean_text, Length: 4589, dtype: object

In [13]:
df['clean_text'] = df['clean_text'].apply(lambda x: nfx.remove_custom_pattern(x, term_pattern=r'&#\S+'))

In [14]:
df['clean_text']

0       b'RT   Ni air starbuck rahsia dari barista. Dr...
1       b'RT   Brewdog is trending because of its awfu...
2       b'The secret recipe to progress - The Up Devot...
3       b'RT   Brewdog is trending because of its awfu...
4       b'RT   New Secret 1.6 Food Recipes\n\xe2\x80\x...
                              ...
4584    b"RT     Is animal cruelty part of   secret re...
4585    b"  Is animal cruelty part of   secret recipe?...
4586    b'RT   i released my secret recipe in the flee...
4587    b'Another Great #RECIPE Post from #FTHM\n\nPle...
4588    b"Me: when I discovered the 'secret recipe' of...
Name: clean_text, Length: 4589, dtype: object

In [15]:
df['clean_text'] = df['clean_text'].apply(lambda x: nfx.remove_custom_pattern(x, term_pattern=r"b'RT"))

In [16]:
df['clean_text'] = df['clean_text'].apply(lambda x: nfx.remove_custom_pattern(x, term_pattern=r'b"RT'))

In [17]:
df['clean_text'] = df['clean_text'].apply(lambda x: nfx.remove_custom_pattern(x, term_pattern=r'b"'))

In [18]:
df['clean_text'] = df['clean_text'].apply(lambda x: nfx.remove_custom_pattern(x, term_pattern=r"b'"))

In [19]:
df['clean_text']

0           Ni air starbuck rahsia dari barista. Drop ...
1           Brewdog is trending because of its awful p...
2        The secret recipe to progress - The Up Devoti...
3           Brewdog is trending because of its awful p...
4           New Secret 1.6 Food Recipes\n\xe2\x80\xa2 ...
                              ...
4584          Is animal cruelty part of   secret recip...
4585       Is animal cruelty part of   secret recipe? ...
4586        i released my secret recipe in the fleets ;)'
4587     Another Great #RECIPE Post from #FTHM\n\nPlea...
4588     Me: when I discovered the 'secret recipe' of ...
Name: clean_text, Length: 4589, dtype: object

In [20]:
df['clean_text'].apply(nfx.remove_special_characters)

0           Ni air starbuck rahsia dari barista Drop y...
1           Brewdog is trending because of its awful p...
2        The secret recipe to progress  The Up Devotio...
3           Brewdog is trending because of its awful p...
4           New Secret 16 Food Recipesnxe2x80xa2 telep...
                              ...
4584          Is animal cruelty part of   secret recip...
4585       Is animal cruelty part of   secret recipe x...
4586           i released my secret recipe in the fleets
4587     Another Great RECIPE Post from FTHMnnPlease C...
4588     Me when I discovered the secret recipe of coc...
Name: clean_text, Length: 4589, dtype: object

In [16]:
import nltk
from __future__ import division
import nltk, re
from nltk import word_tokenize
from nltk import regexp_tokenize
from nltk.tag import pos_tag
from nltk.draw import tree
from nltk.corpus import stopwords

In [26]:
X

0       ni air starbuck rahsia dari barista drop secre...
1       brewdog trending awful practicesnna reminder s...
2       secret recipe progress devotional june 10 prog...
3       brewdog trending awful practicesnna reminder s...
4       new secret 16 food recipesnxe2x80xa2 teleport ...
                              ...
4584    animal cruelty secret recipe xf0x9fx98xa1 http...
4585    animal cruelty secret recipe xf0x9fx98xa1xf0x9...
4586                        released secret recipe fleets
4587    great recipe post fthmnnplease consider sponso...
4588    discovered secret recipe cococola httpstcorjlb...
Name: clean_text, Length: 4589, dtype: object

In [22]:
df['clean_text'] = df['clean_text'].apply(nfx.remove_multiple_spaces)

In [23]:
df.head()

,Unnamed: 0,Time,Id,Username,Text,userhandles,clean_text
0,NaN,6/10/2021 9:07,1.402920e+18,�??�?��?��???�??��??�,b'RT @mhazimhamdan: Ni air starbuck rahsia dar...,[@mhazimhamdan:],Ni air starbuck rahsia dari barista Drop your...
1,0.0,6/10/2021 9:04,1.402910e+18,Richard Gale,b'RT @peteprodge: Brewdog is trending because ...,[@peteprodge:],Brewdog is trending because of its awful prac...
2,1.0,6/10/2021 9:04,1.402910e+18,The Up! Devo,b'The secret recipe to progress - The Up Devot...,[],The secret recipe to progress The Up Devotion...
3,2.0,6/10/2021 9:04,1.402910e+18,Ben Marlow,b'RT @peteprodge: Brewdog is trending because ...,[@peteprodge:],Brewdog is trending because of its awful prac...
4,3.0,6/10/2021 9:01,1.402910e+18,UnLe,b'RT @Davidoooey: New Secret 1.6 Food Recipes\...,[@Davidoooey:],New Secret 16 Food Recipesnxe2x80xa2 teleport...

In [24]:
# Extraction Stopwords
df['clean_text'].apply(lambda x : nt.TextExtractor(x).extract_stopwords())

0                                            [your, from]
1       [is, because, of, its, that, i, have, the, for...
2                                 [the, to, the, up, for]
3       [is, because, of, its, that, i, have, the, for...
4                                     [to, and, from, to]
                              ...
4584                                       [is, part, of]
4585                                       [is, part, of]
4586                                     [i, my, in, the]
4587                              [another, from, us, on]
4588                               [me, when, i, the, of]
Name: clean_text, Length: 4589, dtype: object

In [25]:
# Remove Stopwords
# Method using TextFrame
df['clean_text'].apply(lambda x : nt.TextFrame(x).remove_stopwords())

0       Ni air starbuck rahsia dari barista Drop secre...
1       Brewdog trending awful practicesnnA reminder s...
2       secret recipe progress Devotional June 10 prog...
3       Brewdog trending awful practicesnnA reminder s...
4       New Secret 16 Food Recipesnxe2x80xa2 teleport ...
                              ...
4584    animal cruelty secret recipe xf0x9fx98xa1 http...
4585    animal cruelty secret recipe xf0x9fx98xa1xf0x9...
4586                        released secret recipe fleets
4587    Great RECIPE Post FTHMnnPlease Consider Sponso...
4588    discovered secret recipe cococola httpstcorJLB...
Name: clean_text, Length: 4589, dtype: object

In [26]:
# Remove Stopwords
# Method using Neattext.Functions
df['clean_text'] = df['clean_text'].apply(nfx.remove_stopwords)

In [27]:
df['clean_text'].apply(lambda x : nt.TextFrame(x).noise_scan()['text_noise'])

0       0
1       0
2       0
3       0
4       0
       ..
4584    0
4585    0
4586    0
4587    0
4588    0
Name: clean_text, Length: 4589, dtype: int64

In [28]:
df['clean_text'] = [word.lower() for word in df['clean_text']]
df['clean_text']

0       ni air starbuck rahsia dari barista drop secre...
1       brewdog trending awful practicesnna reminder s...
2       secret recipe progress devotional june 10 prog...
3       brewdog trending awful practicesnna reminder s...
4       new secret 16 food recipesnxe2x80xa2 teleport ...
                              ...
4584    animal cruelty secret recipe xf0x9fx98xa1 http...
4585    animal cruelty secret recipe xf0x9fx98xa1xf0x9...
4586                        released secret recipe fleets
4587    great recipe post fthmnnplease consider sponso...
4588    discovered secret recipe cococola httpstcorjlb...
Name: clean_text, Length: 4589, dtype: object

In [8]:
import text2emotion as te

In [47]:
def getTextEmotion(txt):
    return te.get_emotion(txt)

In [48]:
df['Emotion'] = df['clean_text'].apply(getTextEmotion)

In [49]:
df.to_csv('Test2.csv', header=True, index=False, encoding='utf-8-sig')

In [50]:
df = pd.read_csv("Test2.csv", encoding = 'utf-8', error_bad_lines = False)

In [52]:
df.Emotion.str.split(expand=True)

,0,1,2,3,4,5,6,7,8,9
0,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
1,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
2,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"0.5,",'Sad':,"0.0,",'Fear':,0.5}
3,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
4,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"0.5,",'Sad':,"0.0,",'Fear':,0.5}
...,...,...,...,...,...,...,...,...,...,...
3013,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
3014,{'Happy':,"0.25,",'Angry':,"0.0,",'Surprise':,"0.25,",'Sad':,"0.25,",'Fear':,0.25}
3015,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
3016,{'Happy':,"0.33,",'Angry':,"0.0,",'Surprise':,"0.0,",'Sad':,"0.67,",'Fear':,0.0}
3017,{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}

In [54]:
#Split emotion cloumn into many emotion
df[['Happy_Text','Happy_Value', 'Angry_Text', 'Angry_Value', 
    'Surprise_Text', 'Surprise_Value', 'Sad_Text', 'Sad_Value', 
    'Fear_Text', 'Fear_Value']] = df.Emotion.str.split(" ",expand=True)
df

,clean_text,Emotion,Happy_Text,Happy_Value,Angry_Text,Angry_Value,Surprise_Text,Surprise_Value,Sad_Text,Sad_Value,Fear_Text,Fear_Value
0,ni air starbuck rahsia dari barista drop secre...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
1,brewdog trending awful practicesnna reminder s...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
2,secret recipe progress devotional june 10 prog...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 0.5, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"0.5,",'Sad':,"0.0,",'Fear':,0.5}
3,brewdog trending awful practicesnna reminder s...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
4,new secret 16 food recipes teleport liyue harb...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 0.5, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"0.5,",'Sad':,"0.0,",'Fear':,0.5}
...,...,...,...,...,...,...,...,...,...,...,...,...
3013,awwwww secret recipe,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
3014,harshit makes excellent point when read articl...,"{'Happy': 0.25, 'Angry': 0.0, 'Surprise': 0.25...",{'Happy':,"0.25,",'Angry':,"0.0,",'Surprise':,"0.25,",'Sad':,"0.25,",'Fear':,0.25}
3015,released secret recipe fleets,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}
3016,great recipe post please consider sponsoring,"{'Happy': 0.33, 'Angry': 0.0, 'Surprise': 0.0,...",{'Happy':,"0.33,",'Angry':,"0.0,",'Surprise':,"0.0,",'Sad':,"0.67,",'Fear':,0.0}
3017,discovered secret recipe cococola,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0}

In [55]:
#Clean symbol
df['Happy'] = df['Happy_Value'].str.replace(",", " ")
df['Angry'] = df['Angry_Value'].str.replace(",", " ")
df['Surprise'] = df['Surprise_Value'].str.replace(",", " ")
df['Sad'] = df['Sad_Value'].str.replace(",", " ")
df['Fear'] = df['Fear_Value'].str.replace("}", " ")
df

<ipython-input-55-684cd2f9155c>:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['Fear'] = df['Fear_Value'].str.replace("}", " ")

,clean_text,Emotion,Happy_Text,Happy_Value,Angry_Text,Angry_Value,Surprise_Text,Surprise_Value,Sad_Text,Sad_Value,Fear_Text,Fear_Value,Happy,Angry,Surprise,Sad,Fear
0,ni air starbuck rahsia dari barista drop secre...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0},0.0,0.0,1.0,0.0,0.0
1,brewdog trending awful practicesnna reminder s...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0},0.0,0.0,1.0,0.0,0.0
2,secret recipe progress devotional june 10 prog...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 0.5, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"0.5,",'Sad':,"0.0,",'Fear':,0.5},0.0,0.0,0.5,0.0,0.5
3,brewdog trending awful practicesnna reminder s...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0},0.0,0.0,1.0,0.0,0.0
4,new secret 16 food recipes teleport liyue harb...,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 0.5, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"0.5,",'Sad':,"0.0,",'Fear':,0.5},0.0,0.0,0.5,0.0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3013,awwwww secret recipe,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0},0.0,0.0,1.0,0.0,0.0
3014,harshit makes excellent point when read articl...,"{'Happy': 0.25, 'Angry': 0.0, 'Surprise': 0.25...",{'Happy':,"0.25,",'Angry':,"0.0,",'Surprise':,"0.25,",'Sad':,"0.25,",'Fear':,0.25},0.25,0.0,0.25,0.25,0.25
3015,released secret recipe fleets,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0},0.0,0.0,1.0,0.0,0.0
3016,great recipe post please consider sponsoring,"{'Happy': 0.33, 'Angry': 0.0, 'Surprise': 0.0,...",{'Happy':,"0.33,",'Angry':,"0.0,",'Surprise':,"0.0,",'Sad':,"0.67,",'Fear':,0.0},0.33,0.0,0.0,0.67,0.0
3017,discovered secret recipe cococola,"{'Happy': 0.0, 'Angry': 0.0, 'Surprise': 1.0, ...",{'Happy':,"0.0,",'Angry':,"0.0,",'Surprise':,"1.0,",'Sad':,"0.0,",'Fear':,0.0},0.0,0.0,1.0,0.0,0.0

In [ ]:
# Create a new CSV file 
df.to_csv("Test2.csv", header=True, index=False, encoding='utf-8-sig')